### ISSUE TITLE
Errors creating file 00028874

### ISSUE THREAD

**Issue by Sig2018** [denysvitali/ca-combos-editor#7] opened 2020-09-21 13:59 UTC
Hi Denys,

First to all thank you for your excellent job with this tool!

I was playing with the tool trying to generate mi own 00028874 and after a long way (I'm not familiar with Linux or C++) I was able to make a file with just a few CA combinations on it.

But when I tried to use the original file that came with my Samsung S10e with those few combinations added it was not created.
Please see below the error I got and you can see attached the file with all combinations. The last four are my additions.
Is there any wrong with file ? Thank you in advance for any help you can provide.

C:\Compile\ca-combos-editor-master>go run cmd/main.go create newS10eEdi.txt sali
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/denysvitali/ca-combos-editor/pkg/types.UlArr.Less(...)
        C:/Compile/ca-combos-editor-master/pkg/types/ulentry.go:42
sort.insertionSort(0xef0d80, 0xc0002199e0, 0x0, 0x2)
        c:/go/src/sort/sort.go:27 +0xcc
sort.quickSort(0xef0d80, 0xc0002199e0, 0x0, 0x2, 0x4)
        c:/go/src/sort/sort.go:209 +0x21d
sort.Sort(0xef0d80, 0xc0002199e0)
        c:/go/src/sort/sort.go:218 +0x85
github.com/denysvitali/ca-combos-editor/pkg.ParseBandFile(0xc0000a2080, 0x8, 0x0, 0x0, 0x0)
        C:/Compile/ca-combos-editor-master/pkg/bandparser.go:201 +0x7b6
main.main()
        C:/Compile/ca-combos-editor-master/cmd/main.go:52 +0x354
exit status 2 

[newS10eEdi.zip](https://github.com/denysvitali/ca-combos-editor/files/5255778/newS10eEdi.zip)

**Comment by denysvitali** [comment] 2020-09-21 21:02
Hello Sig2018,

I'm sorry for the bug that you encountered, unfortunately I didn't consider that the class `E` was possible too, therefore your `2A2A-46E2-48C2` combo was being interpreted only as `2A2A` causing a strange behavior. I have now fixed the issue, attached you can find the file generated (even though it's better if you create your own by pulling the new commits and running the software again).
[output.zip](https://github.com/denysvitali/ca-combos-editor/files/5258118/output.zip)

**Comment by denysvitali** [comment] 2020-09-21 21:13
(I'll close this issue, feel free to reopen it if the issue is still not solved)

**Closed as completed by denysvitali** 2020-09-21 21:13 UTC
